apiVersion: v1
kind: Service
metadata:
  name: novelnest-ui
spec:
  selector:
    app: novelnest-ui
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novelnest-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novelnest-ui
  template:
    metadata:
      labels:
        app: novelnest-ui
    spec:
      containers:
        - name: novelnest-ui
          image: quay.io/novelnest/ui:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_USER_SERVICE
              value: "http://localhost:8000/user"
            - name: VITE_INVENTORY_SERVICE
              value: "http://localhost:8000/inventory"
            - name: VITE_CATALOG_SERVICE
              value: "http://localhost:8000/catalog"
            - name: VITE_ORDER_SERVICE
              value: "http://localhost:8000/order"
