apiVersion: batch/v1
kind: Job
metadata:
  name: kong-configurator
spec:
  template:
    metadata:
      name: kong-configurator
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kong-configurator
          image: kong/deck:latest
          command:
            - deck
            - gateway
            - sync
            - /config/kong-declarative-config.yml
            - --kong-addr=http://kong:8001
          volumeMounts:
            - name: kong-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
