apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: quay.io/novelnest/catalog-service:latest
          ports:
            - containerPort: 4000
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: QUEUE_NAME
              value: "messages"
            - name: MONGO_DB
              value: "books_db"
            - name: MONGODB_URI
              value: "mongodb://user:password@mongodb:27017/catalog?authSource=admin"
            - name: JWT_SECRET
              value: "qwertyuiopasdfghjklzxcvbnm123456"
            - name: PORT
              value: "4000"
