apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 5010
      targetPort: 5010
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: quay.io/novelnest/order-service:latest
          ports:
            - containerPort: 5010
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-order:5432/orders_db"
            - name: PORT
              value: "5010"
            - name: JWT_SECRET
              value: "qwertyuiopasdfghjklzxcvbnm123456"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:3000"
      #     volumeMounts:
      #       - name: prisma-vol
      #         mountPath: /app/prisma
      # volumes:
      #   - name: prisma-vol
      #     emptyDir: {}
---

