apiVersion: batch/v1
kind: Job
metadata:
  name: supertokens-admin-create
spec:
  template:
    spec:
      containers:
        - name: supertokens-admin-create
          image: curlimages/curl:latest
          env:
            - name: SUPERTOKENS_CORE_URL
              value: http://supertokens-service:3567
            - name: SUPERTOKENS_DASHBOARD_ADMIN_EMAIL
              value: admin@novelnest.com
            - name: SUPERTOKENS_DASHBOARD_ADMIN_PASSWORD
              value: password123
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔧 Starting supertokens-admin-create to create admin user..." && \
              until curl -s "$${SUPERTOKENS_CORE_URL}/hello" >/dev/null; do
                echo "⏳ Waiting for SuperTokens..." && sleep 2;
              done && \
              echo "✅ SuperTokens is ready. Creating admin user..." && \
              RESPONSE=$$(curl --silent --write-out 'HTTPSTATUS:%{http_code}' --location --request POST "$${SUPERTOKENS_CORE_URL}/recipe/dashboard/user" \
                --header "rid: dashboard" \
                --header "Content-Type: application/json" \
                --data-raw "{\"email\": \"$${SUPERTOKENS_DASHBOARD_ADMIN_EMAIL}\",\"password\": \"$${SUPERTOKENS_DASHBOARD_ADMIN_PASSWORD}\"}") && \
              BODY=$$(echo "$$RESPONSE" | sed -e 's/HTTPSTATUS\:.*//g') && \
              STATUS=$$(echo "$$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://') && \
              if [ "$$STATUS" -eq 200 ]; then \
                if echo "$$BODY" | grep -q "EMAIL_ALREADY_EXISTS_ERROR"; then \
                  echo "ℹ️  Admin user already exists. Skipping creation."; \
                else \
                  echo "✅ Admin user created successfully."; \
                fi; \
              elif echo "$$BODY" | grep -q "PASSWORD_WEAK_ERROR"; then \
                MESSAGE=$$(echo "$$BODY" | sed -n 's/.*\"message\":\"\([^\"]*\)\".*/\1/p'); \
                echo "⚠️  Password is too weak. Reason: $$MESSAGE"; \
                exit 1; \
              else \
                echo "❌ Failed to create admin user. Response:" && echo "$$BODY"; \
                exit 1; \
              fi
      restartPolicy: OnFailure
